export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';
export const FETCH_RENTALS_SUCCESS ='FETCH_RENTALS_SUCCESS';
export const FETCH_RENTALS_FAIL = 'FETCH_RENTALS_FAIL';
export const FETCH_RENTAL_BY_ID_SUCCESS = 'FETCH_RENTAL_BY_ID_SUCCESS';
export const FETCH_RENTAL_BY_ID_FAILS = 'FETCH_RENTAL_BY_ID_FAILS';
export const FETCH_RENTAL_BY_ID_INIT = 'FETCH_RENTAL_BY_ID_INIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT ='LOGOUT';
export const CREATE_RENTAL_INIT ='CREATE_RENTAL_INIT';
export const CREATE_RENTAL_SUCCESS='CREATE_RENTAL_SUCCESS';
export const CREATE_RENTAL_FAILURE = 'CREATE_RENTAL_FAILURE';

// Fetch user booking

export const FETCH_USER_BOOKING_INIT = 'FETCH_USER_BOOKING_INIT';
export const FETCH_USER_BOOKING_SUCCESS ='FETCH_USER_BOOKING_SUCCESS';
export const FETCH_USER_BOOKING_FAILURE='FETCH_USER_BOOKING_FAILURE';

//FETCH USER RENTAL

export const FETCH_USER_RENTAL_INIT ='FETCH_USER_RENTAL_INIT';
export const FETCH_USER_RENTAL_SUCCESS='FETCH_USER_RENTAL_SUCCESS';
export const FETCH_USER_RENTAL_FAILURE ='FETCH_USER_RENTAL_FAILURE';


